### ISSUE TITLE
Blocked 

### ISSUE THREAD

**Issue by bahabryra** [3kh0/3kh0-lite#20]
here do this first go to your website save all the code youve done thus far as a zip file then make it look like a simple education website and then go to https://archive.lightspeedsystems.com/ after that search your url on the url search on the website after that scroll down and click submit for review and then after that it'll be set by a admin so until they figure out the trick we did then it'll be unblocked :)

don't have to just let me know

one more thing delete this issue before submitting for review :)

**Comment by 3kh0** [comment]
Host your own copy of the site to bypass site restrictions
